#!/bin/bash

echo

validateDep=1
# Ant dependency check
if ! which ant &>/dev/null; then
    printf "\tMissing dependency: Ant - Java based build tool\n"
    let validateDep=0
fi
# Ivy dependency check
if ! which ivy &>/dev/null; then
    printf "\tMissing dependency: Ivy - Agile dependency manager\n"
    let validateDep=0
fi
# Java dependency check
if ! which java &>/dev/null; then
    printf "\tMissing dependency: Java\n"
    let validateDep=0
fi

if [ $validateDep -ne 1 ]; then

    echo
    printf "\tExiting...\n";
    echo

    exit 1;
fi

# Build client with ant if not already built
if [ ! -f ./bin/jar/client.jar ]; then
    ant;
    exit 2
fi

clear

eval `resize`
export LINES
export COLUMNS

tput smcup;

java -jar bin/jar/client.jar

tput rmcup;
